kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:

- name: build && test
  image: thomaslacaze/go-opencv-zbar
  pull: always
  commands:
    - go build
    - go test
---


kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:

- name: build && test
  image: thomaslacaze/go-opencv-zbar
  pull: always
  commands:
    - go build
    - go test
---
